services:
  # Nginx
  nginx-webserver:
    image: nginx:1.29.3-alpine
    container_name: nginx-webserver
    hostname: nginx-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src/magento:/var/www/html:cached
      - ./templates/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./templates/nginx/templates/:/etc/nginx/templates
    networks:
      - magento-app-network
    logging:
      options:
        max-size: "10M"
        max-file: "3"
  php-fpm:
    image: ghcr.io/erikngigi/magento-php8.3-fpm:latest
    hostname: magento-php-fpm
    container_name: magento-php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: magento
      SERVICE_TAGS: development
    volumes:
      - ./src/magento:/var/www/html:cached
      # - ./templates/php-config/php.ini-development:/usr/local/etc/php/php.ini:ro
    expose:
      - "9000:9000"
    networks:
      - magento-app-network
    depends_on:
      - db
  db:
    image: mysql:8.0
    hostname: mysql-database
    container_name: mysql-database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      SERVICE_TAGS: development
      SERVICE_NAME: mysql
    networks:
      - magento-app-network
    volumes:
      - db-data:/var/lib/mysql/
      - ./templates/db-init:/docker-entrypoint-initdb.d
  elasticsearch:
    image: elasticsearch:7.17.27
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - magento-app-network
  redis:
    image: redis:7.4-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    tty: true
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - magento-app-network
    volumes:
      - redis-data:/data
networks:
  magento-app-network:
    name: magento-app-network
    driver: bridge
volumes:
  db-data:
    name: mysql-database-volume
    driver: local
  redis-data:
    name: redis-data-volume
    driver: local
