services:
  # Nginx
  nginx-webserver:
    image: nginx:1.29.3-alpine
    container_name: nginx-webserver
    hostname: nginx-webserver
    restart: unless-stopped
    tty: true
    environment:
      AKENEO_PHP_FPM_PORT: ${AKENEO_PHP_FPM_PORT}
      AKENEO_DOMAIN: ${AKENEO_DOMAIN}
      AKENEO_DIRECTORY: ${AKENEO_DIRECTORY}
      MAGENTO_PHP_FPM_PORT: ${MAGENTO_PHP_FPM_PORT}
      MAGENTO_DOMAIN: ${MAGENTO_DOMAIN}
      MAGENTO_DIRECTORY: ${MAGENTO_DIRECTORY}
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src/magento/magento2:/var/www/html/magento2:cached
      - ./src/akeneo/akeneo7:/var/www/html/akeneo7:cached
      - ./templates/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates/nginx/templates/:/etc/nginx/templates
      - ./templates/nginx/certs:/etc/nginx/certs:ro
    networks:
      - akeneo-magento-app-network
    depends_on:
      - magento-php-fpm
      - akeneo-php-fpm
    logging:
      options:
        max-size: "10M"
        max-file: "3"
  # Magento
  magento-php-fpm:
    image: ghcr.io/erikngigi/magento-php-fpm:8.3
    hostname: magento-php-fpm
    container_name: magento-php-fpm
    restart: unless-stopped
    tty: true
    user: "1000:1000" # Run container as your host user
    command: >
      sh -c "chown -R magento:magento /var/www/html && php-fpm"

    volumes:
      - ./src/magento:/var/www/html:cached
      - ./templates/php/php/magento/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./templates/php/php-fpm.d/magento/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./templates/php/php-fpm.d/magento/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    ports:
      - "9050:9050"
    networks:
      - akeneo-magento-app-network
  # Akeneo
  akeneo-php-fpm:
    image: ghcr.io/erikngigi/akeneo-php-fpm:8.1
    hostname: akeneo-php-fpm
    container_name: akeneo-php-fpm
    restart: unless-stopped
    tty: true
    user: "1000:1000" # Run container as your host user
    command: >
      sh -c "chown -R www-data:www-data /var/www/html && php-fpm"

    volumes:
      - ./src/akeneo:/var/www/html:cached
      - ./templates/php/php/akeneo/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./templates/php/php-fpm.d/akeneo/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./templates/php/php-fpm.d/akeneo/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    ports:
      - "9000:9000"
    networks:
      - akeneo-magento-app-network
  # MySQL
  mysql-db:
    image: mysql:8.0
    hostname: mysql-database
    container_name: mysql-database
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - akeneo-magento-app-network
    volumes:
      - db-data:/var/lib/mysql/
      - ./templates/mysql:/docker-entrypoint-initdb.d
    depends_on:
      - akeneo-php-fpm
      - magento-php-fpm
  # Elasticsearch
  elasticsearch:
    image: elasticsearch:7.17.27
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9250:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - akeneo-magento-app-network
    depends_on:
      - akeneo-php-fpm
      - magento-php-fpm
  # Redis
  redis:
    image: redis:7.4-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    tty: true
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - akeneo-magento-app-network
    volumes:
      - redis-data:/data
    depends_on:
      - akeneo-php-fpm
      - magento-php-fpm
networks:
  akeneo-magento-app-network:
    name: akeneo-magento-app-network
    driver: bridge
volumes:
  db-data:
    name: mysql-database-volume
    driver: local
  redis-data:
    name: redis-data-volume
    driver: local
