services:
  # Magento
  magento-php-fpm:
    image: ghcr.io/erikngigi/magento-php-fpm:8.3
    hostname: magento-php-fpm
    container_name: magento-php-fpm
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/magento:/home/magento/magento2:cached
      - ./templates/php/php/magento/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./templates/php/php-fpm.d/magento/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    ports:
      - "127.0.0.1:9050:9050"
    networks:
      - akeneo-magento-app-network
  # Akeneo
  akeneo-php-fpm:
    image: ghcr.io/erikngigi/akeneo-php-fpm:8.1
    hostname: akeneo-php-fpm
    container_name: akeneo-php-fpm
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/akeneo:/home/akeneo/akeneo7:cached
      - ./templates/php/php/akeneo/php.ini-development:/usr/local/etc/php/php.ini:ro
      - ./templates/php/php-fpm.d/akeneo/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - akeneo-magento-app-network
  # MySQL
  mysql-db:
    image: mysql:8.0
    hostname: mysql-database
    container_name: mysql-database
    restart: unless-stopped
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - akeneo-magento-app-network
    volumes:
      - db-data:/var/lib/mysql/
      - ./templates/mysql:/docker-entrypoint-initdb.d
      - ./templates/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    depends_on:
      - akeneo-php-fpm
      - magento-php-fpm
  # Elastisearch
  elasticsearch:
    image: elasticsearch:7.17.27
    hostname: elasticsearch
    container_name: elasticsearch
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - akeneo-magento-app-network
    depends_on:
      - akeneo-php-fpm
      - magento-php-fpm
  # Redis
  redis:
    image: redis:7.4-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    tty: true
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    expose:
      - "6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - akeneo-magento-app-network
    volumes:
      - redis-data:/data
    depends_on:
      - akeneo-php-fpm
      - magento-php-fpm
networks:
  akeneo-magento-app-network:
    name: akeneo-magento-app-network
    driver: bridge
volumes:
  db-data:
    name: mysql-database-volume
    driver: local
  redis-data:
    name: redis-data-volume
    driver: local
